#cloud-config
package_update: true
packages:
  - epel-release
  - openmpi
  - openmpi-devel
  - munge
  - munge-libs
  - slurm
  - slurm-slurmd
  - iperf3
  - nc

users:
  - name: rocky
    ssh_authorized_keys:
      - ${cluster_pub}

write_files:
  - path: /etc/hosts
    permissions: '0644'
    content: |
      127.0.0.1   localhost
      ${hosts_file}

runcmd:
  - [ bash, -lc, "sudo sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config" ]
  - [ bash, -lc, "sudo sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config" ]
  - [ bash, -lc, "echo 'AddressFamily inet' | sudo tee -a /etc/ssh/sshd_config" ]
  - [ bash, -lc, "sudo systemctl reload sshd || sudo systemctl reload ssh" ]
  - [ bash, -lc, "id -u munge >/dev/null 2>&1 || sudo useradd -r -s /sbin/nologin munge" ]
  - [ bash, -lc, "id -u slurm >/dev/null 2>&1 || sudo useradd -r -s /sbin/nologin slurm" ]
  - [ bash, -lc, "echo 'export PATH=/usr/lib64/openmpi/bin:$PATH' | sudo tee /etc/profile.d/mpi.sh" ]
  - [ bash, -lc, "echo 'export LD_LIBRARY_PATH=/usr/lib64/openmpi/lib:$LD_LIBRARY_PATH' | sudo tee -a /etc/profile.d/mpi.sh" ]
